import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import SessionWrapper from "./components/sessionwrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Get Me a Chai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-slate-950`}>

        <Navbar />
        <SessionWrapper>
          {children}
          </SessionWrapper>

      </body>
    </html>
  );
}
